[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bonding_curve = "CB18NKSvKunD2xeuvEkKfBxuz4fJFJJ8GPy5w1dMzN1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[provider.testnet]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[provider.mainnet-beta]
cluster = "mainnet-beta"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
